---
# Setup Percona XtraDB Cluster

- name: Install Percona XtraDB Cluster server
  apt: name=percona-xtradb-cluster-56

- name: Stop XtraDB
  shell: /etc/init.d/mysql stop

- name: Add config
  template: src=pxc.cnf.j2 dest=/etc/mysql/conf.d/pxc.cnf

- name: Add authorized key
  authorized_key: user=vagrant key="{{ lookup('file', 'pxc_id_rsa.pub') }}"
